version: '2'
services:
  db:
    image: postgres:12
    volumes:
      - './db:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: farm
      POSTGRES_PASSWORD: farm
      POSTGRES_DB: farm

  www:
    depends_on:
      - db
    image: farmos/farmos:2.x-dev
    entrypoint: /bin/bash
    command:
      - -c
      - |
        set -ex

        wait_db_ready() {
            while { ! exec 3<>/dev/tcp/db/5432; } > /dev/null 2>&1; do sleep 0.1; done
        }

        if [ -d /opt/drupal ] && ! [ "$$(ls -A /opt/drupal/)" ]; then
          echo "farmOS codebase not detected. Copying from pre-built files in the Docker image."
          cp -rp /var/farmOS/. /opt/drupal
          wait_db_ready
          su www-data -s /bin/bash -c 'drush site-install farm --locale=en --db-url=pgsql://farm:farm@db/farm --site-name=Test0 --account-name=root --account-pass=test'
        fi

        rm -rf /opt/drupal/web/libraries/farmOS-map
        ln -sf /opt/testing_src_tree/farmOS-map /opt/drupal/web/libraries/farmOS-map
        ln -sf /opt/testing_src_tree/farmOS.map.behaviors.wkt.js /opt/drupal/web/profiles/farm/modules/core/map/js/farmOS.map.behaviors.wkt.js
        ln -sf /opt/testing_src_tree/farmOS.map.behaviors.geofield.js /opt/drupal/web/profiles/farm/modules/core/map/js/farmOS.map.behaviors.geofield.js
        ln -sf /opt/testing_src_tree/farm_map.libraries.yml /opt/drupal/web/profiles/farm/modules/core/map/farm_map.libraries.yml

        wait_db_ready

        su www-data -s /bin/bash <<'EOF'
            set -e

            composer config repositories.farmos_dev_modules '{"type": "path", "url": "/farmos_dev_modules/farmos_land_drawing_tool"}'

            composer require symbioquine/farmos_land_drawing_tool @dev

            drush --root=/opt/drupal pm-enable farmos_land_drawing_tool
        EOF

        exec docker-entrypoint.sh apache2-foreground
    volumes:
      - './www:/opt/drupal'
      - './php-custom.ini:/usr/local/etc/php/conf.d/php-custom.ini'
      - '../farmos_land_drawing_tool:/farmos_dev_modules/farmos_land_drawing_tool'
      # Patched versions of farmOS-map and farmOS
      - '../../farmOS/modules/core/map/js/farmOS.map.behaviors.wkt.js:/opt/testing_src_tree/farmOS.map.behaviors.wkt.js'
      - '../../farmOS/modules/core/map/js/farmOS.map.behaviors.geofield.js:/opt/testing_src_tree/farmOS.map.behaviors.geofield.js'
      - '../../farmOS/modules/core/map/farm_map.libraries.yml:/opt/testing_src_tree/farm_map.libraries.yml'
      - '../../farmOS-map:/opt/testing_src_tree/farmOS-map'
    ports:
      - '80:80'
    environment:
      XDEBUG_CONFIG: remote_host=172.22.0.1
      FARMOS_FS_READY_SENTINEL_FILENAME: /opt/drupal/www-container-fs-ready
