version: '2'
services:
  db:
    image: postgres:12
    volumes:
      - './db:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: farm
      POSTGRES_PASSWORD: farm
      POSTGRES_DB: farm

  www:
    depends_on:
      - db
    image: farmos/farmos:2.x-dev
    entrypoint: /bin/bash
    command:
      - -c
      - |
        set -ex

        wait_db_ready() {
            while { ! exec 3<>/dev/tcp/db/5432; } > /dev/null 2>&1; do sleep 0.1; done
        }

        link_srcs() {
          rm -rf /opt/drupal/web/libraries/farmOS-map
          ln -sf /opt/testing_src_tree/farmOS-map /opt/drupal/web/libraries/farmOS-map

          rm -rf /opt/drupal/web/profiles/farm/modules
          ln -sf /opt/testing_src_tree/farmOS/modules /opt/drupal/web/profiles/farm/modules

          rm -rf /opt/drupal/web/profiles/farm/config
          ln -sf /opt/testing_src_tree/farmOS/config /opt/drupal/web/profiles/farm/config

          rm -rf /opt/drupal/web/profiles/farm/src
          ln -sf /opt/testing_src_tree/farmOS/src /opt/drupal/web/profiles/farm/src

          rm -rf /opt/drupal/web/profiles/farm/{farm.info.yml,farm.install,farm.profile}
          ln -sf /opt/testing_src_tree/farmOS/farm.info.yml /opt/drupal/web/profiles/farm/farm.info.yml
          ln -sf /opt/testing_src_tree/farmOS/farm.install /opt/drupal/web/profiles/farm/farm.install
          ln -sf /opt/testing_src_tree/farmOS/farm.profile /opt/drupal/web/profiles/farm/farm.profile
          ln -sf /opt/testing_src_tree/farmOS/composer.json /opt/drupal/web/profiles/farm/composer.json
        }

        if [ -d /opt/drupal ] && ! [ "$$(ls -A /opt/drupal/)" ]; then
          echo "farmOS codebase not detected. Copying from pre-built files in the Docker image."
          cp -rp /var/farmOS/. /opt/drupal

          link_srcs
          wait_db_ready

          su www-data -s /bin/bash -c 'drush site-install farm --locale=en --db-url=pgsql://farm:farm@db/farm --site-name=Test0 --account-name=root --account-pass=test'
        fi

        wait_db_ready

        su www-data -s /bin/bash <<'EOF'
            set -e

            composer config repositories.farmos_dev_modules '{"type": "path", "url": "/farmos_dev_modules/farmos_land_drawing_tool"}'

            composer require symbioquine/farmos_land_drawing_tool @dev

            drush --root=/opt/drupal pm-enable farmos_land_drawing_tool
        EOF

        exec docker-entrypoint.sh apache2-foreground
    volumes:
      - './www:/opt/drupal'
      - './php-custom.ini:/usr/local/etc/php/conf.d/php-custom.ini'
      - '../farmos_land_drawing_tool:/farmos_dev_modules/farmos_land_drawing_tool'
      # Patched versions of farmOS-map and farmOS
      - '../../farmOS-map:/opt/testing_src_tree/farmOS-map'
      - '../../farmOS:/opt/testing_src_tree/farmOS'
    ports:
      - '80:80'
    environment:
      XDEBUG_CONFIG: remote_host=172.22.0.1
      FARMOS_FS_READY_SENTINEL_FILENAME: /opt/drupal/www-container-fs-ready
